// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EnterSearch: typeof import('./src/components/EnterSearch.vue')['default']
    FilterInput: typeof import('./src/components/FilterInput.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InformationSearch: typeof import('./src/components/InformationSearch.vue')['default']
    InformationTable: typeof import('./src/components/InformationTable.vue')['default']
    MyList: typeof import('./src/components/MyList.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
